### ISSUE TITLE
import don't work (I base on Meteor)

### ISSUE THREAD

**Issue by thearabbit** [eliep/vue-avatar#22] opened 2017-10-26 05:01 UTC
I base on `Meteor`
```js
<avatar :username="fullName"></avatar>
-----
import Avatar from 'vue-avatar';

components: {
            avatar: Avatar.Avatar,
```
Get error
```js
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```

**Comment by saintplay** [comment] 2017-10-26 15:44
Duplicate of #21

**Closed** 2017-11-15 02:54 UTC
